<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite903e718c74edb372f477e6b13cbbe3a
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PragmaRX\\Google2FA\\' => 19,
            'ParagonIE\\ConstantTime\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PragmaRX\\Google2FA\\' => 
        array (
            0 => __DIR__ . '/..' . '/pragmarx/google2fa/src',
        ),
        'ParagonIE\\ConstantTime\\' => 
        array (
            0 => __DIR__ . '/..' . '/paragonie/constant_time_encoding/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
		
		
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite903e718c74edb372f477e6b13cbbe3a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite903e718c74edb372f477e6b13cbbe3a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite903e718c74edb372f477e6b13cbbe3a::$classMap;

        }, null, ClassLoader::class);
    }
}
